name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x' 
    - name: Build
      run: dotnet build src/DataModelTools.sln --configuration Release