name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' 
    
    - name: Build
      run: dotnet build src/DataModelTools.sln --configuration Release
    
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.15.2 -DirectDownload -OutputDirectory .
    
    - name: Run UnitTests
      run: ./NUnit.ConsoleRunner.3.15.2/tools/nunit3-console.exe src/Extractor.Tests/bin/Release/net6.0/Extractor.Tests.dll
